import { Language, VillainType } from './types';

// CONFIGURATION: Replace these with your actual links!
export const PAYMENT_CONFIG = {
  creemUrl: "https://www.creem.io/your-profile", // Replace with your Creem.io link
  stripeUrl: "https://buy.stripe.com/your-link", // Replace with your Stripe Payment Link
  wechatQr: "https://via.placeholder.com/300?text=WeChat+Pay+QR", // Replace with your actual QR code image URL
  alipayQr: "https://via.placeholder.com/300?text=Alipay+QR",    // Replace with your actual QR code image URL
  freeCredits: 1, // Number of free tries per session
};

export const TRANSLATIONS = {
  en: {
    title: "VillainSmash",
    subtitle: "Digital Stress Relief Ritual",
    start: "Enter the Temple",
    inputTitle: "Who (or what) is disturbing your peace?",
    nameLabel: "Name of the Villain / Problem",
    typeLabel: "Type of Disturbance",
    reasonLabel: "Why do they deserve the shoe? (Optional)",
    placeholderName: "e.g., My Micromanaging Boss, Procrastination",
    placeholderReason: "e.g., Calling me at 9 PM on Friday...",
    submit: "Begin Ritual",
    generating: "Summoning the Spirits...",
    hitInstruction: "Tap the Villain to Strike!",
    hitsRemaining: "Hits Remaining",
    finish: "Ritual Complete",
    resolving: "Cleansing the Aura...",
    playAgain: "Perform Another Ritual",
    // Conceptual Villain Options (Safe & Fun)
    conceptualVillains: {
      monday: "Monday Syndrome",
      overtime: "Useless Overtime",
      clientPie: "Client's Empty Promises",
      talkOnly: "All Talk No Action",
      badLuck: "Bad Romance",
      procrastination: "Procrastination",
      micromanagement: "Micromanagement",
      gaslighting: "Gaslighting",
      ghosting: "Ghosting",
      cancel: "Last Minute Cancel"
    },
    conceptualVillainDesc: "We're not hitting people, we're hitting bad vibes!",
    // Cyber Talismans (Random Drops)
    talismans: {
      hairLoss: "Anti-Hair Loss Talisman",
      raise: "Salary Raise Talisman",
      noReply: "No-Reply Talisman",
      enjoyLife: "Eat & Drink Freely Talisman",
      goodSleep: "Deep Sleep Talisman",
      focus: "Focus Mode Talisman",
      chill: "Chill Out Talisman",
      lucky: "Lucky Day Talisman",
      money: "Money Flow Talisman"
    },
    talismanDrop: "🎉 Talisman Dropped!",
    talismanCollected: "✓ Collected",
    disclaimer: "⚠️ IMPORTANT NOTICE: This is a digital entertainment tool for psychological stress relief. \n\n1. This is NOT real witchcraft or sorcery - it has no supernatural effect on any person.\n2. This is NOT a platform for harassment, threats, or hate speech.\n3. Entering real personal names of others is STRICTLY PROHIBITED.\n4. If you experience persistent distress, please seek professional mental health support.\n5. Use responsibly - this is for entertainment only.\n\nBy checking the box below, you acknowledge and agree to these terms.",
    disclaimerTitle: "⚠️ Important Disclaimer",
    agreeLabel: "I understand and agree to use this app responsibly",
    mentalHealthNote: "💚 Remember: This is just for fun. If you're feeling overwhelmed, talking to a real person or professional can help.",
    contentWarning: "⚠️ Content Warning: Do NOT enter real names of actual people. This is a fictional game.",
    credits: "Karma Credits",
    outOfCredits: "Out of Karma Credits",
    recharge: "Recharge Karma",
    paymentTitle: "Offer Tribute to the Spirits",
    paymentDesc: "Your spiritual energy is depleted. Make an offering to continue the ritual.",
    payChina: "China (WeChat/Alipay)",
    payGlobal: "Global (Card/Crypto)",
    payWithCreem: "Support via Creem.io",
    payWithStripe: "Pay $0.99 via Stripe",
    scanToPay: "Scan QR Code to Support",
    iHavePaid: "I Have Completed the Offering",
    freeTrialEnded: "Free Trial Ended",
    historyTitle: "Book of Grudges",
    noHistory: "No spirits sealed yet.",
    loadRecord: "Summon Again",
    deleteRecord: "Burn Record",
    openHistory: "View Records",
    screenshotShare: "Screenshot this Talisman to Share Luck",
    liveTicker: [
      "User 29** just banished a Toxic Boss.",
      "Someone in NY just cleared Bad Luck.",
      "A student just hit Procrastination 100 times.",
      "User 88** just sealed a Fake Friend.",
      "Spiritual energy is high today."
    ],
    types: {
      [VillainType.BOSS]: "Toxic Boss / Colleague",
      [VillainType.EX_PARTNER]: "Toxic Ex-Partner",
      [VillainType.FAKE_FRIEND]: "Backstabber / Fake Friend",
      [VillainType.BAD_HABIT]: "Bad Habit / Addiction",
      [VillainType.GENERAL_ANXIETY]: "General Anxiety / Bad Luck",
    },
    // New Social Translations
    shareTitle: "Call for Backup!",
    shareDesc: "Invite friends to help you smash this villain.",
    shareMessage: "I can't take it anymore! Help me beat '{name}' in this digital ritual. Click to join the fight!",
    copied: "Link Copied!",
    assistWelcome: "⚠️ Backup Requested",
    assistDesc: "Your friend needs your help to banish '{name}'.",
    assistAction: "Help Smash It!",
    youHelped: "You Helped Banish Evil!",
    createYourOwn: "Start My Own Ritual",
    // Onboarding Translations (Redesigned - Scientific Stress Relief)
    onboardingTitle: "🔮 Stress Analysis · Quick Diagnosis",
    onboardingSubtitle: "Based on behavioral psychology, analyze your stress patterns and find relief strategies",
    step1Title: "Step 1: Basic Info",
    step1Desc: "Tell us a bit about yourself to personalize your stress relief",
    step2Title: "Step 2: Stress Types",
    step2Desc: "What types of stress are you experiencing?",
    step3Title: "Step 3: Environment",
    step3Desc: "Your daily habits and environment affect stress levels",
    step4Title: "Step 4: Relief Strategy",
    step4Desc: "Generate your personalized stress relief plan",
    next: "Next",
    prev: "Previous",
    submitDiagnosis: "Generate Strategy",
    skipOnboarding: "Skip, Start Directly",
    age: "Age",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    sleepPattern: "Sleep Pattern",
    exercise: "Exercise",
    socialActivity: "Social Activity",
    stressTypes: {
      work: "Work Stress",
      relationship: "Relationship Issues",
      health: "Health Concerns",
      finance: "Financial Pressure",
      study: "Academic Pressure",
      anxiety: "Anxiety",
      insomnia: "Sleep Issues",
      anger: "Anger Management"
    },
    sleepPatterns: {
      early: "Early Bird (before 7am)",
      normal: "Normal (7-9am)",
      late: "Night Owl (after 9am)"
    },
    exerciseLevels: {
      none: "No Exercise",
      light: "Light (1-2x/week)",
      moderate: "Moderate (3-5x/week)",
      heavy: "Heavy (6+x/week)"
    },
    socialLevels: {
      low: "Low",
      moderate: "Moderate",
      high: "High"
    },
    personalityTypes: {
      wood: "Growth Type",
      fire: "Passion Type",
      earth: "Stability Type",
      metal: "Precision Type",
      water: "Adaptability Type"
    },
    directions: {
      north: "North",
      south: "South",
      east: "East",
      west: "West",
      northeast: "Northeast",
      southeast: "Southeast",
      northwest: "Northwest",
      southwest: "Southwest"
    },
    troubles: {
      insomnia: 'Insomnia',
      anxiety: 'Anxiety',
      anger: 'Easily Angry',
      work: 'Work Issues',
      relationship: 'Relationship Problems',
      health: 'Health Issues',
      money: 'Financial Problems',
      study: 'Academic Issues'
    },
    // DiagnosisBook Translations (Redesigned - Scientific Stress Relief)
    diagnosisTitle: "📜 Stress Relief Strategy",
    diagnosisSubtitle: "Based on behavioral psychology and personality analysis",
    userAttribute: "Your Profile",
    birthYear: "Birth Year",
    heavenlyStem: "Personality Trait",
    earthlyBranch: "Behavior Pattern",
    element: "Personality Type",
    currentSituation: "Current Stress Level",
    conflict: "Stress Pattern",
    description: "Analysis",
    villainInfo: "Stress Source",
    villainDirection: "Primary Trigger",
    villainType: "Stress Type",
    villainCharacteristics: "Characteristics",
    solution: "Relief Strategy",
    shoeType: "Relief Tool",
    optimalTime: "Optimal Time",
    psychologicalEffect: "Psychological Insight",
    startRitual: "Start Relief",
    retryDiagnosis: "Retake Analysis",
    elements: {
      wood: "Wood",
      fire: "Fire",
      earth: "Earth",
      metal: "Metal",
      water: "Water"
    }
  },
  zh: {
    title: "打小人在线",
    subtitle: "赛博驱邪 · 心理宣泄",
    start: "进入神庙",
    inputTitle: "谁在扰乱你的安宁？",
    nameLabel: "小人姓名 / 烦恼名称",
    typeLabel: "小人类型",
    reasonLabel: "为什么要打？(选填)",
    placeholderName: "例如：爱开会的老板，拖延症",
    placeholderReason: "例如：周五晚上九点给我打电话...",
    submit: "开始仪式",
    generating: "正在请神...",
    hitInstruction: "点击小人，用力打！",
    hitsRemaining: "剩余击打次数",
    finish: "仪式完成",
    resolving: "净化磁场...",
    playAgain: "再打一次",
    // 概念化小人选项（安全且有趣）
    conceptualVillains: {
      monday: "周一综合症",
      overtime: "无效加班",
      clientPie: "甲方画饼",
      talkOnly: "只说不做",
      badLuck: "烂桃花",
      procrastination: "拖延症",
      micromanagement: "事必躬亲",
      gaslighting: "PUA",
      ghosting: "已读不回",
      cancel: "临时取消"
    },
    conceptualVillainDesc: "我们打的不是人，是晦气！",
    // 赛博护身符（随机掉落）
    talismans: {
      hairLoss: "防脱发符",
      raise: "加薪符",
      noReply: "不回消息符",
      enjoyLife: "该吃吃该喝喝符",
      goodSleep: "深睡符",
      focus: "专注符",
      chill: "躺平符",
      lucky: "转运符",
      money: "暴富符"
    },
    talismanDrop: "🎉 护身符掉落！",
    talismanCollected: "✓ 已收集",
    disclaimer: "⚠️ 重要提示：本应用是一款用于心理压力释放的数字娱乐工具。\n\n1. 这不是真正的巫术——对任何人都没有超自然效果。\n2. 这不是骚扰、威胁或仇恨言论的平台。\n3. 严禁输入他人的真实姓名。\n4. 如果您持续感到困扰，请寻求专业心理健康支持。\n5. 请理性使用——本应用仅供娱乐。\n\n勾选下方即表示您理解并同意这些条款。",
    disclaimerTitle: "⚠️ 重要免责声明",
    agreeLabel: "我理解并承诺负责任地使用此应用",
    mentalHealthNote: "💚 温馨提示：这只是娱乐。如果您感到压力过大，与朋友倾诉或寻求专业帮助会更好。",
    contentWarning: "⚠️ 内容警示：请勿输入真实人名，这只是一款虚拟游戏。",
    credits: "功德点数",
    outOfCredits: "功德不足",
    recharge: "补充功德",
    paymentTitle: "请神需供奉",
    paymentDesc: "您的免费次数已用完。请随喜香火钱，继续驱邪。",
    payChina: "国内支付 (微信/支付宝)",
    payGlobal: "国际支付 (海外)",
    payWithCreem: "通过 Creem.io 赞助",
    payWithStripe: "Stripe 支付 (推荐)",
    scanToPay: "扫码支付香火钱",
    iHavePaid: "我已完成支付",
    freeTrialEnded: "免费试用结束",
    historyTitle: "小人名册",
    noHistory: "暂无封印记录",
    loadRecord: "拖出再打",
    deleteRecord: "销毁记录",
    openHistory: "查看小人名册",
    screenshotShare: "截图保存此符 · 分享转运",
    liveTicker: [
      "北京网友 刚刚暴打了 缺德前任",
      "上海网友 刚刚封印了 唠叨上司",
      "广州网友 正在清理 职场小人",
      "深圳网友 刚刚击退了 水逆霉运",
      "杭州网友 刚刚打了 虚伪朋友 50下",
      "成都网友 刚刚消除了 焦虑情绪",
      "今日香火旺盛，宜打小人"
    ],
    types: {
      [VillainType.BOSS]: "职场小人 / 恶霸老板",
      [VillainType.EX_PARTNER]: "烂桃花 / 前任",
      [VillainType.FAKE_FRIEND]: "虚伪朋友 / 背后捅刀",
      [VillainType.BAD_HABIT]: "坏习惯 / 自身惰性",
      [VillainType.GENERAL_ANXIETY]: "水逆 / 焦虑 / 霉运",
    },
    // New Social Translations
    shareTitle: "急急如律令 · 摇人助阵",
    shareDesc: "一个人的力量不够？召唤好友一起来打！",
    shareMessage: "气死我了！我正在打小人【{name}】，快来帮我补两刀！点击链接直接开打！",
    copied: "链接已复制，快发给朋友！",
    assistWelcome: "⚠️ 紧急助阵模式",
    assistDesc: "你的朋友火力不足，急需你帮忙一起封印【{name}】！",
    assistAction: "替天行道，打！",
    youHelped: "助阵成功 · 功德无量",
    createYourOwn: "我也要打小人",
    // Onboarding Translations (Redesigned - Scientific Stress Relief)
    onboardingTitle: "🔮 压力分析 · 快速诊断",
    onboardingSubtitle: "基于行为心理学，分析你的压力模式，找到缓解策略",
    step1Title: "第一步：基本信息",
    step1Desc: "告诉我们一些关于你的信息，个性化你的压力缓解方案",
    step2Title: "第二步：压力类型",
    step2Desc: "你正在经历哪些类型的压力？",
    step3Title: "第三步：环境因素",
    step3Desc: "你的日常习惯和环境会影响压力水平",
    step4Title: "第四步：缓解策略",
    step4Desc: "生成你的个性化压力缓解计划",
    next: "下一步",
    prev: "上一步",
    submitDiagnosis: "【生成策略】",
    skipOnboarding: "跳过，直接开始",
    age: "年龄",
    gender: "性别",
    male: "男",
    female: "女",
    other: "其他",
    sleepPattern: "作息模式",
    exercise: "运动习惯",
    socialActivity: "社交活动",
    stressTypes: {
      work: "工作压力",
      relationship: "感情困扰",
      health: "健康担忧",
      finance: "经济压力",
      study: "学业压力",
      anxiety: "焦虑情绪",
      insomnia: "睡眠问题",
      anger: "情绪管理"
    },
    sleepPatterns: {
      early: "早起型（7点前）",
      normal: "正常型（7-9点）",
      late: "晚睡型（9点后）"
    },
    exerciseLevels: {
      none: "不运动",
      light: "轻度（每周1-2次）",
      moderate: "中度（每周3-5次）",
      heavy: "重度（每周6次以上）"
    },
    socialLevels: {
      low: "较少",
      moderate: "适中",
      high: "频繁"
    },
    personalityTypes: {
      wood: "成长型",
      fire: "激情型",
      earth: "稳定型",
      metal: "精准型",
      water: "适应型"
    },
    directions: {
      north: "正北",
      south: "正南",
      east: "正东",
      west: "正西",
      northeast: "东北",
      southeast: "东南",
      northwest: "西北",
      southwest: "西南"
    },
    troubles: {
      insomnia: "失眠多梦",
      anxiety: "心烦意乱",
      anger: "容易发火",
      work: "职场不顺",
      relationship: "感情困扰",
      health: "身体不适",
      money: "财运不佳",
      study: "学业受阻"
    },
    // DiagnosisBook Translations (Redesigned - Scientific Stress Relief)
    diagnosisTitle: "📜 压力缓解策略",
    diagnosisSubtitle: "基于行为心理学和人格分析",
    userAttribute: "你的档案",
    birthYear: "出生年份",
    heavenlyStem: "人格特质",
    earthlyBranch: "行为模式",
    element: "人格类型",
    currentSituation: "当前压力水平",
    conflict: "压力模式",
    description: "分析",
    villainInfo: "压力源",
    villainDirection: "主要触发因素",
    villainType: "压力类型",
    villainCharacteristics: "特征",
    solution: "缓解策略",
    shoeType: "缓解工具",
    optimalTime: "最佳时机",
    psychologicalEffect: "心理洞察",
    startRitual: "【开始缓解】",
    retryDiagnosis: "【重新分析】",
    elements: {
      wood: "木",
      fire: "火",
      earth: "土",
      metal: "金",
      water: "水"
    }
  }
};

export const TOTAL_HITS_REQUIRED = 20;