export const COUNTRY_NAMES: Record<string, string> = {
    'CN': 'China',
    'US': 'United States',
    'TW': 'Taiwan',
    'HK': 'Hong Kong',
    'JP': 'Japan',
    'KR': 'South Korea',
    'GB': 'United Kingdom',
    'CA': 'Canada',
    'SG': 'Singapore',
    'MY': 'Malaysia',
    'AU': 'Australia',
    'DE': 'Germany',
    'FR': 'France',
    'IT': 'Italy',
    'ES': 'Spain',
    'NL': 'Netherlands',
    'SE': 'Sweden',
    'NO': 'Norway',
    'FI': 'Finland',
    'DK': 'Denmark',
    'PL': 'Poland',
    'CZ': 'Czech Republic',
    'AT': 'Austria',
    'CH': 'Switzerland',
    'BE': 'Belgium',
    'IE': 'Ireland',
    'PT': 'Portugal',
    'GR': 'Greece',
    'TR': 'Turkey',
    'RU': 'Russia',
    'UA': 'Ukraine',
    'IN': 'India',
    'ID': 'Indonesia',
    'PH': 'Philippines',
    'VN': 'Vietnam',
    'TH': 'Thailand',
    'PK': 'Pakistan',
    'BD': 'Bangladesh',
    'LK': 'Sri Lanka',
    'NP': 'Nepal',
    'MM': 'Myanmar',
    'KH': 'Cambodia',
    'LA': 'Laos',
    'BN': 'Brunei',
    'MV': 'Maldives',
    'BT': 'Bhutan',
    'AF': 'Afghanistan',
    'IR': 'Iran',
    'IQ': 'Iraq',
    'SA': 'Saudi Arabia',
    'AE': 'United Arab Emirates',
    'QA': 'Qatar',
    'KW': 'Kuwait',
    'OM': 'Oman',
    'BH': 'Bahrain',
    'JO': 'Jordan',
    'LB': 'Lebanon',
    'SY': 'Syria',
    'IL': 'Israel',
    'EG': 'Egypt',
    'MA': 'Morocco',
    'DZ': 'Algeria',
    'TN': 'Tunisia',
    'LY': 'Libya',
    'SD': 'Sudan',
    'ET': 'Ethiopia',
    'KE': 'Kenya',
    'NG': 'Nigeria',
    'ZA': 'South Africa',
    'GH': 'Ghana',
    'CI': 'Ivory Coast',
    'SN': 'Senegal',
    'ML': 'Mali',
    'BF': 'Burkina Faso',
    'NE': 'Niger',
    'TD': 'Chad',
    'CM': 'Cameroon',
    'CG': 'Republic of the Congo',
    'CD': 'Democratic Republic of the Congo',
    'AO': 'Angola',
    'MZ': 'Mozambique',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
    'BW': 'Botswana',
    'NA': 'Namibia',
    'MG': 'Madagascar',
    'MU': 'Mauritius',
    'AR': 'Argentina',
    'BR': 'Brazil',
    'CL': 'Chile',
    'CO': 'Colombia',
    'PE': 'Peru',
    'VE': 'Venezuela',
    'EC': 'Ecuador',
    'BO': 'Bolivia',
    'PY': 'Paraguay',
    'UY': 'Uruguay',
    'GY': 'Guyana',
    'SR': 'Suriname',
    'GF': 'French Guiana',
    'MX': 'Mexico',
    'GT': 'Guatemala',
    'HN': 'Honduras',
    'SV': 'El Salvador',
    'NI': 'Nicaragua',
    'CR': 'Costa Rica',
    'PA': 'Panama',
    'CU': 'Cuba',
    'DO': 'Dominican Republic',
    'JM': 'Jamaica',
    'TT': 'Trinidad and Tobago',
    'BB': 'Barbados',
    'BS': 'Bahamas',
    'NZ': 'New Zealand',
    'FJ': 'Fiji',
    'PG': 'Papua New Guinea',
    'VU': 'Vanuatu',
    'SB': 'Solomon Islands',
    'WS': 'Samoa',
    'TO': 'Tonga',
    'FM': 'Micronesia',
    'MH': 'Marshall Islands',
    'PW': 'Palau',
    'KI': 'Kiribati',
    'NR': 'Nauru',
    'TV': 'Tuvalu',
    'CK': 'Cook Islands',
    'NU': 'Niue',
    'AS': 'American Samoa',
    'GU': 'Guam',
    'MP': 'Northern Mariana Islands',
    'VI': 'Virgin Islands (U.S.)',
    'PR': 'Puerto Rico',
    'KY': 'Cayman Islands',
    'BM': 'Bermuda',
    'GG': 'Guernsey',
    'JE': 'Jersey',
    'IM': 'Isle of Man',
    'AX': 'Åland Islands',
    'FO': 'Faroe Islands',
    'GL': 'Greenland',
    'IS': 'Iceland',
    'LI': 'Liechtenstein',
    'MC': 'Monaco',
    'SM': 'San Marino',
    'VA': 'Vatican City',
    'AD': 'Andorra',
    'MT': 'Malta',
    'CY': 'Cyprus',
    'AL': 'Albania',
    'MK': 'North Macedonia',
    'ME': 'Montenegro',
    'RS': 'Serbia',
    'BA': 'Bosnia and Herzegovina',
    'HR': 'Croatia',
    'SI': 'Slovenia',
    'SK': 'Slovakia',
    'HU': 'Hungary',
    'RO': 'Romania',
    'BG': 'Bulgaria',
    'MD': 'Moldova',
    'GE': 'Georgia',
    'AM': 'Armenia',
    'AZ': 'Azerbaijan',
    'KZ': 'Kazakhstan',
    'UZ': 'Uzbekistan',
    'KG': 'Kyrgyzstan',
    'TJ': 'Tajikistan',
    'TM': 'Turkmenistan',
    'MN': 'Mongolia',
    'KP': 'North Korea',
    'MO': 'Macau',
    'MV': 'Maldives'
};

export const REGION_NAMES: Record<string, Record<string, string>> = {
    'CN': {
        'BJ': '北京',
        'SH': '上海',
        'GD': '广东',
        'ZJ': '浙江',
        'JS': '江苏',
        'SC': '四川',
        'HB': '湖北',
        'FJ': '福建',
        'SD': '山东',
        'HN': '湖南',
        'AH': '安徽',
        'HA': '河南',
        'HE': '河北',
        'SX': '山西',
        'SN': '陕西',
        'GS': '甘肃',
        'JX': '江西',
        'GX': '广西',
        'YN': '云南',
        'GZ': '贵州',
        'QH': '青海',
        'XJ': '新疆',
        'XZ': '西藏',
        'NM': '内蒙古',
        'LN': '辽宁',
        'JL': '吉林',
        'HL': '黑龙江',
        'HI': '海南',
        'CQ': '重庆',
        'TJ': '天津'
    },
    'US': {
        'CA': 'California',
        'TX': 'Texas',
        'NY': 'New York',
        'FL': 'Florida',
        'IL': 'Illinois',
        'PA': 'Pennsylvania',
        'OH': 'Ohio',
        'GA': 'Georgia',
        'NC': 'North Carolina',
        'MI': 'Michigan',
        'NJ': 'New Jersey',
        'VA': 'Virginia',
        'WA': 'Washington',
        'AZ': 'Arizona',
        'MA': 'Massachusetts',
        'TN': 'Tennessee',
        'IN': 'Indiana',
        'MO': 'Missouri',
        'MD': 'Maryland',
        'WI': 'Wisconsin',
        'CO': 'Colorado',
        'MN': 'Minnesota',
        'AL': 'Alabama',
        'SC': 'South Carolina',
        'LA': 'Louisiana',
        'KY': 'Kentucky',
        'OR': 'Oregon',
        'OK': 'Oklahoma',
        'CT': 'Connecticut',
        'IA': 'Iowa',
        'MS': 'Mississippi',
        'AR': 'Arkansas',
        'KS': 'Kansas',
        'UT': 'Utah',
        'NV': 'Nevada',
        'NM': 'New Mexico',
        'NE': 'Nebraska',
        'WV': 'West Virginia',
        'ID': 'Idaho',
        'HI': 'Hawaii',
        'NH': 'New Hampshire',
        'ME': 'Maine',
        'RI': 'Rhode Island',
        'MT': 'Montana',
        'DE': 'Delaware',
        'SD': 'South Dakota',
        'ND': 'North Dakota',
        'AK': 'Alaska',
        'VT': 'Vermont',
        'WY': 'Wyoming',
        'DC': 'District of Columbia',
        'PR': 'Puerto Rico',
        'GU': 'Guam',
        'VI': 'Virgin Islands',
        'AS': 'American Samoa',
        'MP': 'Northern Mariana Islands'
    },
    'JP': {
        '01': 'Hokkaido',
        '02': 'Aomori',
        '03': 'Iwate',
        '04': 'Miyagi',
        '05': 'Akita',
        '06': 'Yamagata',
        '07': 'Fukushima',
        '08': 'Ibaraki',
        '09': 'Tochigi',
        '10': 'Gunma',
        '11': 'Saitama',
        '12': 'Chiba',
        '13': 'Tokyo',
        '14': 'Kanagawa',
        '15': 'Niigata',
        '16': 'Toyama',
        '17': 'Ishikawa',
        '18': 'Fukui',
        '19': 'Yamanashi',
        '20': 'Nagano',
        '21': 'Gifu',
        '22': 'Shizuoka',
        '23': 'Aichi',
        '24': 'Mie',
        '25': 'Shiga',
        '26': 'Kyoto',
        '27': 'Osaka',
        '28': 'Hyogo',
        '29': 'Nara',
        '30': 'Wakayama',
        '31': 'Tottori',
        '32': 'Shimane',
        '33': 'Okayama',
        '34': 'Hiroshima',
        '35': 'Yamaguchi',
        '36': 'Tokushima',
        '37': 'Kagawa',
        '38': 'Ehime',
        '39': 'Kochi',
        '40': 'Fukuoka',
        '41': 'Saga',
        '42': 'Nagasaki',
        '43': 'Kumamoto',
        '44': 'Oita',
        '45': 'Miyazaki',
        '46': 'Kagoshima',
        '47': 'Okinawa'
    },
    'KR': {
        '11': 'Seoul',
        '26': 'Busan',
        '27': 'Daegu',
        '28': 'Incheon',
        '29': 'Gwangju',
        '30': 'Daejeon',
        '31': 'Ulsan',
        '41': 'Gyeonggi',
        '42': 'Gangwon',
        '43': 'Chungbuk',
        '44': 'Chungnam',
        '45': 'Jeonbuk',
        '46': 'Jeonnam',
        '47': 'Gyeongbuk',
        '48': 'Gyeongnam',
        '49': 'Jeju'
    },
    'GB': {
        'ENG': 'England',
        'SCT': 'Scotland',
        'WLS': 'Wales',
        'NIR': 'Northern Ireland'
    },
    'DE': {
        'BW': 'Baden-Württemberg',
        'BY': 'Bavaria',
        'BE': 'Berlin',
        'BB': 'Brandenburg',
        'HB': 'Bremen',
        'HH': 'Hamburg',
        'HE': 'Hesse',
        'MV': 'Mecklenburg-Vorpommern',
        'NI': 'Lower Saxony',
        'NW': 'North Rhine-Westphalia',
        'RP': 'Rhineland-Palatinate',
        'SL': 'Saarland',
        'SN': 'Saxony',
        'ST': 'Saxony-Anhalt',
        'SH': 'Schleswig-Holstein',
        'TH': 'Thuringia'
    },
    'FR': {
        'IDF': 'Île-de-France',
        'HDF': 'Hauts-de-France',
        'NOR': 'Normandy',
        'GES': 'Grand Est',
        'PAC': 'Provence-Alpes-Côte d\'Azur',
        'OCC': 'Occitanie',
        'NAQ': 'Nouvelle-Aquitaine',
        'BRE': 'Brittany',
        'CVL': 'Centre-Val de Loire',
        'PDL': 'Pays de la Loire',
        'ARA': 'Auvergne-Rhône-Alpes',
        'BFC': 'Bourgogne-Franche-Comté',
        'COR': 'Corsica'
    },
    'CA': {
        'AB': 'Alberta',
        'BC': 'British Columbia',
        'MB': 'Manitoba',
        'NB': 'New Brunswick',
        'NL': 'Newfoundland and Labrador',
        'NS': 'Nova Scotia',
        'NT': 'Northwest Territories',
        'NU': 'Nunavut',
        'ON': 'Ontario',
        'PE': 'Prince Edward Island',
        'QC': 'Quebec',
        'SK': 'Saskatchewan',
        'YT': 'Yukon'
    },
    'AU': {
        'NSW': 'New South Wales',
        'VIC': 'Victoria',
        'QLD': 'Queensland',
        'WA': 'Western Australia',
        'SA': 'South Australia',
        'TAS': 'Tasmania',
        'ACT': 'Australian Capital Territory',
        'NT': 'Northern Territory'
    },
    'IN': {
        'AN': 'Andaman and Nicobar Islands',
        'AP': 'Andhra Pradesh',
        'AR': 'Arunachal Pradesh',
        'AS': 'Assam',
        'BR': 'Bihar',
        'CH': 'Chandigarh',
        'CT': 'Chhattisgarh',
        'DN': 'Dadra and Nagar Haveli and Daman and Diu',
        'DL': 'Delhi',
        'GA': 'Goa',
        'GJ': 'Gujarat',
        'HP': 'Himachal Pradesh',
        'HR': 'Haryana',
        'JH': 'Jharkhand',
        'JK': 'Jammu and Kashmir',
        'KA': 'Karnataka',
        'KL': 'Kerala',
        'LA': 'Ladakh',
        'MP': 'Madhya Pradesh',
        'MH': 'Maharashtra',
        'MN': 'Manipur',
        'ML': 'Meghalaya',
        'MZ': 'Mizoram',
        'NL': 'Nagaland',
        'OR': 'Odisha',
        'PB': 'Punjab',
        'RJ': 'Rajasthan',
        'SK': 'Sikkim',
        'TN': 'Tamil Nadu',
        'TG': 'Telangana',
        'TR': 'Tripura',
        'UP': 'Uttar Pradesh',
        'UT': 'Uttarakhand',
        'WB': 'West Bengal'
    },
    'BR': {
        'AC': 'Acre',
        'AL': 'Alagoas',
        'AP': 'Amapá',
        'AM': 'Amazonas',
        'BA': 'Bahia',
        'CE': 'Ceará',
        'DF': 'Distrito Federal',
        'ES': 'Espírito Santo',
        'GO': 'Goiás',
        'MA': 'Maranhão',
        'MT': 'Mato Grosso',
        'MS': 'Mato Grosso do Sul',
        'MG': 'Minas Gerais',
        'PA': 'Pará',
        'PB': 'Paraíba',
        'PR': 'Paraná',
        'PE': 'Pernambuco',
        'PI': 'Piauí',
        'RJ': 'Rio de Janeiro',
        'RN': 'Rio Grande do Norte',
        'RS': 'Rio Grande do Sul',
        'RO': 'Rondônia',
        'RR': 'Roraima',
        'SC': 'Santa Catarina',
        'SP': 'São Paulo',
        'SE': 'Sergipe',
        'TO': 'Tocantins'
    },
    'MX': {
        'AGU': 'Aguascalientes',
        'BCN': 'Baja California',
        'BCS': 'Baja California Sur',
        'CAM': 'Campeche',
        'CHP': 'Chiapas',
        'CHH': 'Chihuahua',
        'COA': 'Coahuila',
        'COL': 'Colima',
        'DUR': 'Durango',
        'GUA': 'Guanajuato',
        'GRO': 'Guerrero',
        'HID': 'Hidalgo',
        'JAL': 'Jalisco',
        'MEX': 'Mexico City',
        'MIC': 'Michoacán',
        'MOR': 'Morelos',
        'NAY': 'Nayarit',
        'NLE': 'Nuevo León',
        'OAX': 'Oaxaca',
        'PUE': 'Puebla',
        'QUE': 'Querétaro',
        'ROO': 'Quintana Roo',
        'SLP': 'San Luis Potosí',
        'SIN': 'Sinaloa',
        'SON': 'Sonora',
        'TAB': 'Tabasco',
        'TAM': 'Tamaulipas',
        'TLA': 'Tlaxcala',
        'VER': 'Veracruz',
        'YUC': 'Yucatán',
        'ZAC': 'Zacatecas'
    },
    'RU': {
        'AD': 'Adygea',
        'AL': 'Altai',
        'BA': 'Bashkortostan',
        'BU': 'Buryatia',
        'CE': 'Chechnya',
        'CU': 'Chuvashia',
        'DA': 'Dagestan',
        'IN': 'Ingushetia',
        'KB': 'Kabardino-Balkaria',
        'KL': 'Kalmykia',
        'KC': 'Karachay-Cherkessia',
        'KR': 'Karelia',
        'KO': 'Komi',
        'ME': 'Mari El',
        'MO': 'Mordovia',
        'SA': 'Sakha',
        'SE': 'North Ossetia-Alania',
        'TA': 'Tatarstan',
        'TY': 'Tuva',
        'UD': 'Udmurtia',
        'KK': 'Khakassia',
        'CHE': 'Chelyabinsk',
        'YAR': 'Yaroslavl',
        'MOS': 'Moscow',
        'SPE': 'Saint Petersburg'
    }
};

export const getCountryName = (code: string): string => {
    return COUNTRY_NAMES[code] || code;
};

export const getRegionName = (countryCode: string, regionCode: string): string => {
    return REGION_NAMES[countryCode]?.[regionCode] || regionCode;
};
